name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        modname: libox_controller
        enable_coverage: "true"
        git_dependencies: https://github.com/TheEt1234/libox https://github.com/minetest-mods/mesecons https://github.com/minetest-mods/digilines
        additional_config: |
          secure.trusted_mods = "libox"
    - uses: coverallsapp/github-action@v1